services:
  backend:
    build: ./backend
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgres://root:replaceme-pass@db:5432/root
      - DJANGO_ENV=dev
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health/"]
      interval: 10s
      timeout: 5s
      retries: 5  
  
  db:
    image: postgres:18.3-alpine3.22
    shm_size: 128mb
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=replaceme-pass
      - POSTGRES_USER=root
      - POSTGRES_DB=root
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U root -d root"]
      interval: 10s
      timeout: 5s
      retries: 5  

  
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-fI", "http://localhost:80"]
      interval: 10s
      timeout: 5s
      retries: 5  

volumes:
  postgres_data:
    driver: local