[tool.black]
line-length = 88
target-version = ["py312"]

[tool.ruff]
line-length = 88
target-version = "py312"
exclude = ["venv", "node_modules", "migrations"]

[tool.ruff.lint]
select = ["E","F","I","UP","B","C4","PIE","ISC"]
ignore = ["E501"]

[tool.ruff.lint.isort]
known-first-party = ["config"]
combine-as-imports = true


[tool.mypy]
python_version = "3.12"
plugins = ["mypy_django_plugin.main"]
explicit_package_bases = true
files = ["backend"]
ignore_missing_imports = true
strict_optional = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
warn_unused_ignores = true
warn_redundant_casts = true


[tool.django-stubs]
django_settings_module = "backend.config.settings.dev"
