name: Backend CI Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: backend/requirements.txt

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements-dev.txt

      - name: ruff
        working-directory: backend
        run: ruff check .

      - name: black --check
        working-directory: backend
        run: black --check .

      - name: mypy
        run: mypy .
